### ISSUE TITLE
Update to 1.9

### ISSUE THREAD

**Issue by Phreag** [Multiverse/Multiverse-Portals#415]
Ist seems like it is not Working with 1.9
Could you update it?

**Comment by dumptruckman** [comment]
No. You update. http://ci.onarandombox.com

**Comment by Phreag** [comment]
I am already using the latest Build.

[13:58:33] [Server thread/INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.5-b737
[13:58:33] [Server thread/INFO]: [Multiverse-Portals] - Version 2.5-b737 Enabled - By Rigby and fernferret
[13:58:33] [Server thread/ERROR]: Error occurred while enabling Multiverse-Portals v2.5-b737 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.onarandombox.MultiversePortals.MVPortal.addToUpperLists(MVPortal.java:170) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.init(MVPortal.java:101) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:67) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.loadMVPortalFromConfig(MVPortal.java:177) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.loadPortals(MultiversePortals.java:220) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:131) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot.jar:git-Spigot-604e046-69e196f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-604e046-69e196f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-604e046-69e196f]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-604e046-69e196f]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-604e046-69e196f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

**Comment by dumptruckman** [comment]
My apologies. This should have been fixed already but weird build things are occurring it seems. The latest build http://ci.onarandombox.com/job/Multiverse-Portals/ should work.
