### ISSUE TITLE
Doesn't work with 1.8.8

### ISSUE THREAD

**Issue by crazykids2800** [Multiverse/Multiverse-Portals#513]
I have a Spigot server running on 1.8.8. I downloaded it and ran it and the plugin didn't show up. No folder had been created nor had it appeared in /plugins

**Comment by noammeshulam** [comment]
same

**Comment by Jadiction** [comment]
When starting the server, what does the console say when it tries to enable the plugin? What version are you trying? Do you have Multiverse-Core installed already? (This is required for Multiverse-Portals) More information is needed in order to help.

**Comment by noammeshulam** [comment]
thank you for replying!, I am using Spigot-1.13.2.jar , the plugin doesn't
show up when doing /pl and no file (the one with the config.yml) shows up.
I have multiverse-core v2.5.0 and multiverse-portals v4.0.0
multiverse core doesn't show any errors on console
multiverse-portals has an error -


13.07 12:21:17 [Server] ERROR Could not load 'plugins/Multiverse-Portals-4.
0.0.jar' in folder 'plugins' 13.07 12:21:17 [Server] INFO
org.bukkit.plugin.InvalidPluginException:
java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command 13.0
7 12:21:17 [Server] INFO at
org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139)
~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17 [Server] INFO
at
org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:33
2) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17 [Server] INFO
at
org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:2
52) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17 [Server] INFO
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:
325) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17
[Server] INFO
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:2
13) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17 [Server] INFO
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:69
8) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17 [Server] INFO
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] 13.07 12:21:17
[Server] INFO Caused by: java.lang.NoClassDefFoundError:
com/onarandombox/commandhandler/Command 13.07 12:21:17 [Server] INFO at
java.lang.Class.forName0(Native Method) ~[?:1.8.0_212] 13.07 12:21:17
[Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212] 13.0
7 12:21:17 [Server] INFO at
org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:60)
~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17 [Server] INFO
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:
135) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17
[Server] INFO
... 6 more 13.07 12:21:17 [Server] INFO Caused by:
java.lang.ClassNotFoundException: com.onarandombox.commandhandler.Command 1
3.07 12:21:17 [Server] INFO at
java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212] 1
3.07 12:21:17 [Server] INFO at
org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:13
6) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17 [Server] INFO
at
org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82)
~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17 [Server] INFO
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212] 13.0
7 12:21:17 [Server] INFO at
java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] 13.07 1
2:21:17 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_2
12] 13.07 12:21:17 [Server] INFO at java.lang.Class.forName(Class.java:348)
~[?:1.8.0_212] 13.07 12:21:17 [Server] INFO at
org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:60)
~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17 [Server] INFO
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:
135) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3] 13.07 12:21:17
[Server] INFO
... 6 more

**Comment by smallestchild** [comment]
Multiverse-Core 2.5.0 is meant for 1.12 and below while Multiverse-Portals 4.0.0 is meant for 1.13 and above. I would assume that updating MV-Core to the proper version would stop issues with MV-Portals on your 1.13+ server
https://dev.bukkit.org/projects/multiverse-core/files

**Comment by noammeshulam** [comment]
thank you so much (I sometimes forget those lol) it worked and I really
appeciate your help!
Have a nice day!

‫בתאריך שבת, 13 ביולי 2019 ב-22:41 מאת ‪smallestchild‬‏ <‪
notifications@github.com‬‏>:‬
